language: ruby
rvm:
  - ruby-head
  - 2.2.3
  - 2.1.0
  - 1.9.3
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: 1.9.3
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
